---
- name: gather network resources information from routers
  hosts: all
  gather_facts: true

  tasks:
  - name: run show version on remote devices
    cisco.ios.ios_command:
      commands: show version
    when: ('ios' in ansible_network_os)
  
