---
- name: Test show version
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: network_cli

  tasks:
  - name: run show version on remote cisco device
    register: result
    cisco.ios.ios_command:
      commands: show version
    when: ('ios' in ansible_network_os)

  - name: Display version
    ansible.builtin.debug: 
      var: result


  - name: run show version on arista remote device
    register: result
    arista.eos.eos_command:
      commands: show version
    when: ('eos' in ansible_network_os)

  - name: Display version
    ansible.builtin.debug:
      var: result
