---

- block:
    - name: Running deleted - ios_snmp_server - play
      register: result
      cisco.ios.ios_snmp_server:
        config:
        state: deleted

    - name: Display Result
      ansible.builtin.debug:
        var: result

  always:
    - ansible.builtin.include_tasks: _remove_config.yaml
