- name: cisco snmp server configuration
  hosts: cisco
  gather_facts: false

  tasks:
    - ansible.builtin.include_tasks: merged.yaml
    - ansible.builtin.include_tasks: overridden.yaml
    - ansible.builtin.include_tasks: deleted.yaml
    - ansible.builtin.include_tasks: gathered.yaml
