---
- name: Running overriden - ios_snmp_server - play
  register: result
  cisco.ios.ios_snmp_server:
    config:
      location: "location entry for snmp"
      packet_size: 500
      communities:
        - acl_v4: acl_uq
          name: communityOvverriden
          rw: true
    state: overridden

- name: Display Result
  ansible.builtin.debug:
    var: result
