---
- name: Running parsed - ios_snmp_server play
  register: result
  cisco.ios.ios_snmp_server:
    running_config: "{{ lookup('file', '{{ playbook_dir }}/_parsed.cfg') }}"
    state: parsed

- name: Display Result
  ansible.builtin.debug:
    var: result
