---
- name: Ios_snmp_server parsed - play
  register: result
  cisco.ios.ios_snmp_server:
    running_config: "{{ lookup('file', '_parsed.cfg') }}"
    state: parsed

- name: Display Result
  ansible.builtin.debug:
    var: result
