---
- name: ios_hostname deleted - play
  register: result
  cisco.ios.ios_hostname:
    config:
    state: deleted
  when: ('ios' in ansible_network_os)

- name: Display Result
  ansible.builtin.debug:
    var: result

- name: eos_hostname deleted - play
  register: result1
  arista.eos.eos_hostname:
    config:
    state: deleted
  when: ('eos' in ansible_network_os)

- name: Display Result
  ansible.builtin.debug:
    var: result1
