---
- ansible.builtin.include_tasks: _remove_config.yaml
- ansible.builtin.include_tasks: _populate_config.yaml

- block:
    - name: Ios_hostname merged - play
      register: result
      cisco.ios.ios_hostname: &id001
        config:
          hostname: "boxTest"
        state: merged

    - name: Display Result
      ansible.builtin.debug:
        var: result

  always:
    - ansible.builtin.include_tasks: _remove_config.yaml
