---
- name: ios_hostname merged - play
  register: result
  cisco.ios.ios_hostname:
    config:
      hostname: "boxTest"
    state: merged
  when: ('ios' in ansible_network_os)

- name: Display Result
  ansible.builtin.debug:
    var: result

- name: eos_hostname merged - play
  register: result1
  arista.eos.eos_hostname:
    config:
      hostname: "boxTest"
    state: merged
  when: ('eos' in ansible_network_os)

- name: Display Result
  ansible.builtin.debug:
    var: result1
