---
- name: Ios - Delete prefix list based on prefix name configured
  register: result
  cisco.ios.ios_prefix_lists:
    state: deleted
  when: ('ios' in ansible_network_os)

- name: Display result 
  ansible.builtin.debug:
    var: result

- name: EOS - Delete prefix list based on prefix name configured
  register: result1
  arista.eos.eos_prefix_lists:
    state: deleted
  when: ('eos' in ansible_network_os)

- name: Display result 
  ansible.builtin.debug:
    var: result1

