---
- name: IOS - Gather the provided configuration with the existing running configuration
  register: result
  cisco.ios.ios_prefix_lists:
    config:
    state: gathered
  when: ('ios' in ansible_network_os)

- name: Display Result
  ansible.builtin.debug:
    var: result

- name: EOS - Gather the provided configuration with the existing running configuration
  register: result1
  arista.eos.eos_prefix_lists:
    config:
    state: gathered
  when: ('eos' in ansible_network_os)

- name: Display Result
  ansible.builtin.debug:
    var: result1
