- name: prefix-lists configuration
  hosts: all
  gather_facts: false

  tasks:
    - ansible.builtin.include_tasks: merged.yaml
    - ansible.builtin.include_tasks: gathered.yaml
    - ansible.builtin.include_tasks: deleted.yaml
