- name: "Run command and parse with textfsm"
  ansible.utils.cli_parse:
    command: 'show version'
    parser:
      name: ansible.utils.textfsm
      template_path: "{{ playbook_dir }}/cisco/templates/ios_show_version.textfsm"
  register: ios_textfsm_fact

- name: Display fact
  ansible.builtin.debug:
    var: ios_textfsm_fact['parsed']
