- name: cli parse utility plugin
  hosts: all
  gather_facts: false

  tasks:
  - name: Install required python package
    ansible.builtin.pip:
      name: "{{ item }}"
    with_items:
      - genie
      - pyats
    delegate_to: localhost
    ignore_errors: yes

  - block:  
    - ansible.builtin.include_tasks: cisco/pyatsparse.yaml
    - ansible.builtin.include_tasks: cisco/textfsmparse.yaml
    when: ('ios' in ansible_network_os)

  - block:  
    - ansible.builtin.include_tasks: arista/textfsmparse.yaml
    when: ('eos' in ansible_network_os)
