- name: Run command and parse with xml
  ansible.utils.cli_parse:
    command: "show interfaces | xml"
    parser:
      name: ansible.utils.xml
  register: ios_xml_text

- name: Display fact
  ansible.builtin.debug:
    var: ios_xml_fact['parsed']
