- name: Run show version command
  register: previous_command
  cisco.ios.ios_command:
    commands: show version

- name: "textfsm Pass text and command"
  ansible.utils.cli_parse:
    text: "{{ previous_command['stdout'] }}"
    parser:
      name: ansible.utils.textfsm
      template_path: "{{ playbook_dir }}/templates/ios_show_version.textfsm"
  register: ios_textfsm_fact

- name: Display fact
  ansible.builtin.debug:
    var: ios_textfsm_fact
